sudo: false

language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then phpenv config-rm xdebug.ini; fi
  - composer selfupdate
  - composer update --no-interaction

script:
  - ./vendor/phpunit/phpunit/phpunit -v
